### PR TITLE
Show MySQL and PostgreSQL versions

### PR DESCRIPTION
**Pull request by aprescott**
I didn't know of a way to test this out, but if there is one please let me know and I can double check it works fine!

### CODE REVIEW

**Comment by aprescott** [comment]
> if there is one please let me know and I can double check it works fine

I apparently completely missed the `.travis.yml` file!

**Comment by BanzaiMan** [comment]
MySQL part might work, but PostgreSQL, (probably) not so much, since we install multiple versions.

**Comment by aprescott** [comment]
@BanzaiMan is the version not "locked down" as part of the build in such a way that the `postgres` command points to a single version for the build? If a build has `.travis.yml` with

```yaml
addons:
  postgresql: "9.3"
```

I assume `postgres --version` would still report a 9.3 version, even if it's possible that other versions could be given for the `postgresql:` YAML key?

**Comment by BanzaiMan** [comment]
I apologize for not giving this more thought that it deserves. We restructured the app, and this no longer applies.

**Pull request closed without merging**
